{
 "title": "Backup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last Loki Backup Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"Bixu420\", service=\"loki\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Backup Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Bixu420\", service=\"loki\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Prometheus Backup Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Bixu420\", service=\"prometheus\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Last Prometheus Backup Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"Bixu420\", service=\"prometheus\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last MySQL Backup Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"Bixu420\", service=\"mysql\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Backup count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"Bixu420\", service=\"mysql\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}