apiVersion: 1

deleteDatasources: []

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus1
    url: http://{{ service_cnames.prometheus }}.{{ domain }}/prometheus/
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s
      httpMethod: POST
    version: 1
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki1
    url: http://{{ service_cnames.loki }}.{{ domain }}:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
    version: 1