{
 "title": "main",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "KEEPALIVE STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "NGINX STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Docker 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-1.bixu.io:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Haproxy_Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MYSQL STATUS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bind_UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Avability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "100 * (\r\n  sum without (hostname) (rate({job=\"haproxy\"} |~ \" [23][0-9][0-9] \" [10m]))\r\n  /\r\n  sum without (hostname) (rate({job=\"haproxy\"} [10m]))\r\n)"
    }
   ]
  },
  {
   "title": "Docker 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-2.bixu.io:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "promtail_sent_entries_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "rate(promtail_sent_entries_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "loki_log_messages_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(level) (rate(loki_log_messages_total[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BInd Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(bind_resolver_queries_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mysql commands total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(mysql_global_status_commands_total[1m]))\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU UTIL",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM UTIL",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  node_memory_MemAvailable_bytes{instance!=\"localhost:9100\"} \r\n  / \r\n  node_memory_MemTotal_bytes{instance!=\"localhost:9100\"}\r\n))\r\n\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "agama latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(\r\n  avg_over_time(\r\n    {job=\"haproxy\"}\r\n    | regexp \" (?P<status>[0-9]{3}) (?P<tr>[0-9]+)$\"\r\n    | unwrap tr\r\n    [10m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "NGINX requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}