{
 "title": "MYSQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Slave sql running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MYSQL STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": " historical data for MySQL replication threads ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql_global_variables_read_only",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mysql server Id",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql commands rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[5m])",
     "legendFormat": "{{instance}} : {{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\"}[5m])\r\n",
     "legendFormat": "{{instance}} : {{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\"}[5m])",
     "legendFormat": "{{instance}} : {{command}}"
    }
   ]
  }
 ]
}